export default {

	LOAD_REQUEST: 'LOAD_REQUEST',
	REFRESH_REQUEST: 'REFRESH_REQUEST',
	ACCEPT_REQUEST: 'ACCEPT_REQUEST',
	CANCEL_REQUEST: 'CANCEL_REQUEST',
	REJECT_REQUEST: 'REJECT_REQUEST',
	SUBMIT_REQUEST: 'SUBMIT_REQUEST',
}