export default {

	GO_BACK: 'GO_BACK',
	GOTO_ID: 'GOTO_ID',
	GOTO_REQUEST: 'GOTO_REQUEST',
	GOTO_PROFILE: 'GOTO_PROFILE',
	GOTO_MESSAGES: 'GOTO_MESSAGES',
	GOTO_SEARCH: 'GOTO_SEARCH',
	GOTO_ADD_REQUEST: 'GOTO_ADD_REQUEST',
	GOTO_ADD_MEMBER: 'GOTO_ADD_MEMBER',
	GOTO_ADD_SERVICES: 'GOTO_ADD_SERVICES',
}
